### ISSUE TITLE
INSTALL ERROR

### ISSUE THREAD

**Issue by bwmoths** [verticalphotoplacer/VerticalPhotoPlacerPlugin#2]
Whilst trying to install Vertical Photo Placer on QGIS 3.20.3 I get this error _

Couldn't load plugin 'vertical_photo_placer' due to an error when calling its classFactory() method 

Exception: Cannot find exiftool, make sure to add exiftool to the system path variable. 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vertical_photo_placer\__init__.py", line 41, in classFactory
    from .vertical_photo_placer import VerticalPhotoPlacer
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vertical_photo_placer\vertical_photo_placer.py", line 46, in 
    from .model.process_metadata import ProcessMetadata
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vertical_photo_placer\model\process_metadata.py", line 31, in 
    from .pyexiftool import ExifTool
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vertical_photo_placer\model\pyexiftool.py", line 97, in 
    executable = resolveTool("exiftool")
  File "C:\Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vertical_photo_placer\model\utility.py", line 103, in resolveTool
    raise Exception('Cannot find {0}, make sure to add {1} to the system path variable.'.format(prog, prog))
Exception: Cannot find exiftool, make sure to add exiftool to the system path variable.

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.20.3-Odense Odense, 495fbaec 

Python Path:
C:\Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\TomBio
C:\Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenTopography-DEM-Downloader
C:\Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:\Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\dms_2_deg
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
C:/Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.20.3\bin\python39.zip
C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.20.3\bin
C:\PROGRA~1\QGIS32~1.3\apps\Python39
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by mdchuc** [comment]
Hi, maybe you want to install ExifTool first. Please follow this instruction.
[VPP User guide](https://verticalphotoplacer.github.io/VerticalPhotoPlacer/)

**Comment by bwmoths** [comment]
Hi I have ExifTool installed on my laptop (?), so will see if your instructions make any difference. Cheers

**Comment by bwmoths** [comment]
Hi 
 
Not being a regular user of GitHub - How do I download the ".ExifTool_config" file ? Can't see a 'download' button or similar ?
 
Cheers 
Martin




> Hi, maybe you want to install ExifTool first. Please follow this instruction.
> VPP User guide
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.

--

**Comment by mdchuc** [comment]
Hi, maybe just copy the content, then on your computer create a new file named ".ExifTool_config" and paste the content to it.

**Comment by bwmoths** [comment]
Hi Again
 
Thanks for last message. Haven't managed to get the exiftool config file copied etc., but, discovered that the 'ExifTool' .exe file installed by the Windows installer was called exiftool(-k).exe, when this file was renamed as exiftool.exe the plugin installed apparently correctly.
 
VPP plugin looks OK now on my copy of QGIS but I have not had the chance to try it a set of photos so maybe the lack of the exiftool config file might yet prove to be a problem ?
 
Will let you know !!!!!!!!!!


Martin




> Hi, maybe just copy the content, then on your computer create a new file named ".ExifTool_config" and paste the content to it.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.

--

**Comment by mdchuc** [comment]
Hi, config file is needed for altitude correction, but for the default function it is not needed.
I am looking forward to your result!!

**Comment by sbonaime** [comment]
Hi,
I have the same "Exception: Cannot find exiftool, make sure to add exiftool to the system path variable. " error on my mac.
Python version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
QGIS version: 3.28.0-Firenze Firenze, ed3ad0430f 

I followed the installation instruction with the PATH
<img width="699" alt="Capture d’écran 2022-11-24 à 15 24 52" src="https://user-images.githubusercontent.com/750709/203784070-9b5c0052-a3ab-41d5-b4d8-64412d99c1da.png">

<img width="311" alt="Capture d’écran 2022-11-24 à 15 13 04" src="https://user-images.githubusercontent.com/750709/203782892-3d4bac9c-12e0-408a-b836-7152dbbd170d.png">

I also downloaded the .ExifTool_config that I put in the exiftool directory 
<img width="556" alt="Capture d’écran 2022-11-24 à 15 13 32" src="https://user-images.githubusercontent.com/750709/203782951-12b179ad-8f7e-4f08-beec-29aa1e59ae8f.png">

I restarted QGIS and I still have this error. Anything wrong ? 
Thanks

**Comment by sbonaime** [comment]
I found my problem ! 
I installed exiftool using brew. Brew has its own way of managing bin files and create links to the bin files in
/usr/local/bin/
The links point to the executables files in my case to /usr/local/bin/Cellar/exiftool/12.50/bin/exiftool

 /usr/local/bin/ ll exiftool
lrwxr-xr-x  1 bonaime  admin    37B Nov 21 18:33 exiftool -> ../Cellar/exiftool/12.50/bin/exiftool

So my solution is to put
```:/usr/local/bin/Cellar/exiftool/12.50/bin```
in the PATH field. 
But maybe something would be change in the code to be able to put symbolic link also. If I pupgrade exiftool, I will need to change it's path in QGIS. If QGIS can understand symbolic link, I will hae nothing to do. I will have a look at the code

**Comment by gioman** [comment]
Same thing here. Exiftool (and the compation config file) are inside a folder in c:\ and the path variable has been correctly set (exiftool can be used from the Windows terminal). Regardless the plugin returns an error on QGIS start. Please advise.

![image](https://github.com/verticalphotoplacer/VerticalPhotoPlacer/assets/1951107/13971e1d-5e08-45cd-98c8-02fc6883b4f6)

![image](https://github.com/verticalphotoplacer/VerticalPhotoPlacer/assets/1951107/a9e22d24-673f-4d59-9208-5b39ebbd56b9)


```
Exception: Cannot find exiftool, make sure to add exiftool to the system path variable. 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vertical_photo_placer\__init__.py", line 41, in classFactory
    from .vertical_photo_placer import VerticalPhotoPlacer
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vertical_photo_placer\vertical_photo_placer.py", line 46, in 
    from .model.process_metadata import ProcessMetadata
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vertical_photo_placer\model\process_metadata.py", line 31, in 
    from .pyexiftool import ExifTool
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vertical_photo_placer\model\pyexiftool.py", line 97, in 
    executable = resolveTool("exiftool")
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vertical_photo_placer\model\utility.py", line 103, in resolveTool
    raise Exception('Cannot find {0}, make sure to add {1} to the system path variable.'.format(prog, prog))
Exception: Cannot find exiftool, make sure to add exiftool to the system path variable.
```
